### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by quasiperfect** [webgriffe/SyliusBackInStockNotificationPlugin#44]
hi

thanks for you code any idea how to solve this ?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires webgriffe/sylius-back-in-stock-notification-plugin ^3.0 -> satisfiable by webgriffe/sylius-back-in-stock-notification-plugin[3.0.0].
    - webgriffe/sylius-back-in-stock-notification-plugin 3.0.0 requires symfony/config ^5.4 -> found symfony/config[v5.4.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.2.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require webgriffe/sylius-back-in-stock-notification-plugin:*" to figure out if any version is installable, or "composer require webgriffe/sylius-back-in-stock-notification-plugin:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by lamasfoker** [comment]
Hi @quasiperfect, I will take a look at it on monday

**Comment by lorenzo-shots** [comment]
I resolved the composer install problem, I had one similar to the @quasiperfect 's problem doing as suggested: 
`composer require webgriffe/sylius-back-in-stock-notification-plugin:*"`

But after creating the two files as mentioned in the install procedure (the files are: `config/routes/webgriffe_sylius_back_in_stock_notification_plugin.yaml` and `config/packages/webgriffe_sylius_back_in_stock_notification_plugin.yaml`, I can't  execute the migrations (the ... doctrine:migrations:migrate command) as I get the error:
` Cannot load migrations from "/srv/sylius/vendor/webgriffe/sylius-back-in-stock-notification-plugin/Migrations" because it is not a valid directory`. Any help or hint? Thank you in advance.

**Comment by oallain** [comment]
Hello @lamasfoker ,

I've made a PR #47 to fix it.

Regards,
