### ISSUE TITLE
Add a spam anti bot

### ISSUE THREAD

**Issue by zangra-dev** [webgriffe/SyliusBackInStockNotificationPlugin#8]
Hello, 
we are using the plugin since one month (it's work super well) and the first bot come to add their fake mail on the DB.

I would like to propose the following code to counter this (I will not make a PR because our branches are very differents and the code is easy to adapt)

In productSubscriptionForm.html.twig , add just after the form_start
```
<p style="display:none;">
    <label for="customer_email">Email : </label><input type="email" id="customer_email" name="customer_email">
</p>
```
And in the first line of addAction in the SubscriptionController.php
```
$spam = $request->request->get("customer_email");
if (!empty($spam)) {
    return $this->redirect($this->getRefererUrl($request));
}
```

With this, the bot will enter data in the customer_email field and if there is something in this field, the code will not process the function's rest and come back to the product page. Of course it's not visible for other clients

**Comment by lamasfoker** [comment]
Hi @zangra-dev, thanks for opening the issue. I think it is not the duty of the plugin to handle the bots. I think that should be a measure that the user of the plugin (web developer) should implement in all of the website forms in a consistent way. 
In the Symfony world, there are a lot of alternatives and I think that the user of our plugin should rely on them or otherwise use a custom implementation. I list 3 goods Symfony Bundle:
1. [EoHoneypotBundle](https://github.com/eymengunay/EoHoneypotBundle) adds a Honeypot field Type, it is like your proposal;
2. [Gregwar's CaptchaBundle](https://github.com/Gregwar/CaptchaBundle) adds a Captcha field Type;
3. [EWZRecaptchaBundle](https://github.com/excelwebzone/EWZRecaptchaBundle) adds a ReCaptcha field Type (Google Captcha).

But thanks again for the suggestion.
